In [1]:
#Supporting Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#Keras
from keras.layers import Dense
from keras.utils import to_categorical
from keras.models import Sequential
from keras.callbacks import EarlyStopping

C:\Users\Andri\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [2]:
df = pd.read_csv('dataset.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,...,13291,13292,13293,13294,13295,13296,13297,13298,13299,label
0,0,1,1,1,1,1,1,1,2,1,...,199,203,204,198,200,203,199,194,191,0
1,118,123,119,118,121,121,119,125,126,147,...,159,165,174,165,144,164,179,178,177,1
2,147,74,104,166,209,226,182,111,217,222,...,232,232,234,239,231,237,239,232,231,1
3,178,177,171,172,174,171,161,161,158,159,...,11,11,13,19,19,13,21,13,7,0
4,183,184,189,182,180,180,179,182,179,179,...,32,32,35,35,32,42,38,33,33,0

In [3]:
y = to_categorical(df['label'])
X = df.drop('label',axis=1).as_matrix()
X = np.multiply(X, 1/255)

In [4]:
#Model
model = Sequential()

#1st layer
model.add(Dense(50, activation='relu', input_shape=(X.shape[1],)))

#2nd layer
model.add(Dense(50, activation='relu'))

#3nd layer
model.add(Dense(50, activation='relu'))

#output layer
model.add(Dense(2, activation='softmax'))

#compile
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

#Training
early_stopping_monitor = EarlyStopping(patience=3)

model.fit(X, y, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

Train on 101 samples, validate on 26 samples
Epoch 1/30
101/101 [==============================] - 1s 6ms/step - loss: 0.8437 - acc: 0.6931 - val_loss: 0.5800 - val_acc: 0.8462
Epoch 2/30
101/101 [==============================] - 0s 1ms/step - loss: 0.5412 - acc: 0.8119 - val_loss: 1.0025 - val_acc: 0.2308
Epoch 3/30
101/101 [==============================] - 0s 1ms/step - loss: 0.6535 - acc: 0.6238 - val_loss: 0.3295 - val_acc: 0.9231
Epoch 4/30
101/101 [==============================] - 0s 1ms/step - loss: 0.8416 - acc: 0.7525 - val_loss: 0.2674 - val_acc: 0.9231
Epoch 5/30
101/101 [==============================] - 0s 2ms/step - loss: 0.4954 - acc: 0.7426 - val_loss: 0.3179 - val_acc: 0.9615
Epoch 6/30
101/101 [==============================] - 0s 1ms/step - loss: 0.4572 - acc: 0.8218 - val_loss: 0.2373 - val_acc: 0.9231
Epoch 7/30
101/101 [==============================] - 0s 1ms/step - loss: 0.3004 - acc: 0.8812 - val_loss: 0.3719 - val_acc: 0.8462
Epoch 8/30
101/101 [==============================] - 0s 1ms/step - loss: 0.2787 - acc: 0.9010 - val_loss: 0.3266 - val_acc: 0.9231
Epoch 9/30
101/101 [==============================] - 0s 1ms/step - loss: 0.2882 - acc: 0.8713 - val_loss: 0.4047 - val_acc: 0.8462

In [5]:
model.save('3layers-50nodes.h5')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 50)                665050
_________________________________________________________________
dense_2 (Dense)              (None, 50)                2550
_________________________________________________________________
dense_3 (Dense)              (None, 50)                2550
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 102
=================================================================
Total params: 670,252
Trainable params: 670,252
Non-trainable params: 0
_________________________________________________________________